### ISSUE TITLE
[BUG] Los `ActivityRecord` creados no se muestran en la versión `1.0.0-beta+2`

### ISSUE THREAD

**Issue by refmv** [Frozen-Burrito/hydrate-app#23]
**Descripción del Error**
Cuando se introducen los datos de un `ActivityRecord` en `NewActivityForm` y se presiona el botón "Crear", la app redirige a la vista principal, pero al navegar a la **pestaña de historial** el nuevo registro no se muestra.

**Cómo Reproducir**
Pasos para reproducir el error:
1. Compilar e iniciar la app como release.
2. Navegar a formulario para crear un nuevo `ActivityRecord`.
3. Completar los campos.
4. Observar mensajes de advertencia generados por `ValidationMessageBuilder`, con cada cambio en el formulario.
5. Presionar el botón "crear".
6. Notar el mensaje de error producido por una excepción `Bad state: no element` en `SQLiteDB.select()`, línea 214 de `sqlite_db.dart`.
7. Navegar a la pestaña de historial de actividad física.
8. Observar que no hay una tarjeta para la actividad creada.

**Comportamiento Esperado**
La app debería mostrar todos los `ActivityRecord` en la pestaña de historial de actividad. Además, `ValidationMessageBuilder` no debería recibir errores de validación de tipo `NumericInputError.isNaN` cuando valida la duración, distancia o kilocalorías de un registro de actividad física, y menos si los valores del fomrulario son correctos.

**Entorno **
 - Dispositivo: Galaxy A30
 - OS: Android 11
 - Versión de la app: 1.0.0-beta+2

**Contexto Adicional**
Al parecer, este error solo ha sido observado en la versión `release` de la app. En modo `debug` no ha aparecido.

Los mensajes de error completos:

```
I/flutter ( 3002): Unhandled activity record duration validation message for error: NumericInputError.isNaN
I/flutter ( 3002): Unhandled activity record distance validation message for error: NumericInputError.isNaN
I/flutter ( 3002): Unhandled activity record kCal validation message for error: NumericInputError.isNaN
```

```
I/flutter ( 3002): Query result example: {id: 1, titulo: Paseo, fecha: 2022-08-25T14:04:00.000, duracion: 20, distancia: 1.6666666666666665, kilocalorias_quemadas: 80, al_aire_libre: 1, es_rutina: 0, id_tipo_actividad: 0, id_perfil: 0}
E/flutter ( 3002): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Bad state: No element
E/flutter ( 3002): #0      ListMixin.firstWhere (dart:collection/list.dart:167)
E/flutter ( 3002): #1      SQLiteDB.select (package:hydrate_app/src/db/sqlite_db.dart:214)
E/flutter ( 3002): <asynchronous suspension>
E/flutter ( 3002): #2      ActivityProvider._queryActivityRecords (package:hydrate_app/src/provider/activity_provider.dart:151)
E/flutter ( 3002): <asynchronous suspension>
E/flutter ( 3002): #3      CacheState.refresh (package:hydrate_app/src/provider/cache_state.dart:126)
E/flutter ( 3002): <asynchronous suspension>
```

**Comment by refmv** [comment]
Posiblemente hacen falta pruebas unitarias para `ActivityValidator`, especialmente para sus funciones de validación de duración, distancia y kCal.

**Comment by refmv** [comment]
Los mensajes de error producidos por `ActivityValidator` son causados por no especificar el parámetro `includesUnits` como `true` cuando los valores incluyen unidades, como `72 kCal`. Las pruebas unitarias para `ActivityValidator` son correctas.

**Comment by refmv** [comment]
El error en `SQLiteDB` es causado por la forma en se obtienen los datos del `ActivityRecord` antes de guardarlo en `NewActivityForm`.  

`NewActivityForm` no actualiza el ID del perfil activo correctamente, aún cuando se invoca `ProfileProvider.changeProfile()`. Solo lo obtiene una vez, cuando es construido al inicio. Como al crear un perfil inicial, su ID es 1 y no 0, el valor usado por `NewActivityForm` es el viejo ID de perfil, antes de que el usuario creara su perfil.

Esto explica por qué el error sucedía cuando el usuario recién creaba un perfil inicial. Se solucionó haciendo que `NewProfileForm` obtenga el ID del perfil activo usando `ProfileProvider`, en vez de hacerlo por su constructor.
