### ISSUE TITLE
[BUG] Excepción no manejada en `MainView`: "Looking up a deactivated widget's ancestor is unsafe."

### ISSUE THREAD

**Issue by refmv** [Frozen-Burrito/hydrate-app#41]
**Descripción del Error**
El método `_showGuidesDialog()` de `MainView` produce una excepción no manejada al usar un contexto obsoleto (probablemente después de un async gap). Este error también es provocado por el método `_showDialogIfReportAvailable()`.

**Cómo Reproducir**
Pasos para reproducir el error:
1. Abrir la app.
2. Navegar a una vista que no sea `MainView` (como la vista de login o la de ajustes).
3. Regresar a la `MainView`
4. Ver el error en debug output.

**Comportamiento Esperado**
El método `_showGuidesDialog()` debe mostrar, bajo ciertas condiciones, un `AlertDialog` preguntando al usuario si desea consultar las guías de usuario online. No debería acceder a un `BuildContext` obsoleto.

**Entorno**
 - Dispositivo: Galaxy A30s
 - OS: Android 11
 - Versión de la app: 1.0.0+1

**Contexto Adicional**
Mensaje de la excepción en la consola:
```
E/flutter (11861): [ERROR:flutter/lib/ui/ui_dart_state.cc(198)] Unhandled Exception: Looking up a deactivated widget's ancestor is unsafe.
E/flutter (11861): At this point the state of the widget's element tree is no longer stable.
E/flutter (11861): To safely refer to a widget's ancestor in its dispose() method, save a reference to the ancestor by calling dependOnInheritedWidgetOfExactType() in the widget's didChangeDependencies() method.
E/flutter (11861): #0      Element._debugCheckStateIsActiveForAncestorLookup.<anonymous closure>
package:flutter/…/widgets/framework.dart:4186
E/flutter (11861): #1      Element._debugCheckStateIsActiveForAncestorLookup
package:flutter/…/widgets/framework.dart:4200
E/flutter (11861): #2      Element.getElementForInheritedWidgetOfExactType
package:flutter/…/widgets/framework.dart:4226
E/flutter (11861): #3      Provider._inheritedElementOf
package:provider/src/provider.dart:339
E/flutter (11861): #4      Provider.of
package:provider/src/provider.dart:293
E/flutter (11861): #5      MainView._showGuidesDialog
package:hydrate_app/…/views/main_view.dart:27
E/flutter (11861): #6      MainView.build.<anonymous closure>
package:hydrate_app/…/views/main_view.dart:94
E/flutter (11861): #7      new Future.delayed.<anonymous closure> (dart:async/future.dart:423:39)
E/flutter (11861): #8      _rootRun (dart:async/zone.dart:1418:47)
E/flutter (11861): #9      _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter (11861): #10     _CustomZone.runGuarded (dart:async/zone.dart:1236:7)
E/flutter (11861): #11     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1276:23)
E/flutter (11861): #12     _rootRun (dart:async/zone.dart:1426:13)
E/flutter (11861): #13     _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter (11861): #14     _CustomZone.bindCallback.<anonymous closure> (dart:async/zone.dart:1260:23)
E/flutter (11861): #15     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
E/flutter (11861): #16     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
E/flutter (11861): #17     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
E/flutter (11861): #18     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:192:12)
```

**Comment by refmv** [comment]
Solucionado usando `Future.microtask()` en vez de `Future.delayed()` para mostrar los dialogs de la vista principal, además de arreglar el uso de `context` para no usar contextos obsoletos.
